api_platform:
    title: Music API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
    enable_swagger_ui: true
    enable_docs: true
    enable_entrypoint: false
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    show_webby: false # Hides the API Platform logo
    formats:
        jsonld: ["application/ld+json"]
        json: ["application/json"]
