controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
auth:
    path: /api/auth
    methods: ["POST"]
api_docs:
    path: /api/docs
    controller: api_platform.swagger_ui.action
redirect_to_docs:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: "api_docs"
        permanent: true
